### ISSUE TITLE
typo? fasle

### ISSUE THREAD

**Issue by phenomeus** [rench/homebridge-smarthome#14]
/usr/lib/node_modules/homebridge-smarthome/kit/mijia/airpurifier.js:236
            callback(null, **fasle**);
                           ^

ReferenceError: fasle is not defined
    at Characteristic.service_led.getCharacteristic.on.on (/usr/lib/node_modules/homebridge-smarthome/kit/mijia/airpurifier.js:236:28)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:856:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:801:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by rench** [comment]
try update to 1.1.3
