### ISSUE TITLE
Throw new error

### ISSUE THREAD

**Issue by mouali92** [rench/homebridge-smarthome#6]
Hi there,

I keep getting the same error. Even after reinstalling my raspberry and only installing the plugin. The error that i get is:

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at Characteristic.service_air.getCharacteristic.on (/usr/local/lib/node_modules/homebridge-smarthome/kit/mijia/airpurifier.js:112:13)
    at emitThree (events.js:121:20)
    at Characteristic.emit (events.js:194:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:129:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:627:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:591:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)

Hope that someone can help me.

**Comment by rench** [comment]
yes,i found there are some duplicated code,so i remove these section and publish 1.0.7,please update and try again. thanks for your issue.

**Comment by mouali92** [comment]
Hi, thank you for your respons.

I installed the update and in terminal it seems to run fine but the homekit app shows all devices are not responding. As soon as I touch the air purifier button the error message shows again:


/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at Characteristic.service_air.getCharacteristic.on (/usr/local/lib/node_modules/homebridge-smarthome/kit/mijia/airpurifier.js:119:11)
    at emitThree (events.js:116:13)
    at Characteristic.emit (events.js:194:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:129:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:627:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:591:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)

**Comment by rench** [comment]
aha,there are multi callback section which i have not deal.
update and try it.
thanks.
